### PR TITLE
Moving to auditwheel 5.0.0

### PR DESCRIPTION
**Pull request by asenyaev**
Fix an issue https://github.com/opencv/opencv-python/issues/572

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@skvark could you look at it too.

**Comment by skvark** [comment]
Code looks ok to me but `imshow` should be tested manually on similar systems as in the linked issue. I can try on Ubuntu later this week when I have more time.

**Comment by asmorkalov** [comment]
@skvark Thanks for the review. We are working on test system to check the issue manually.

**Comment by asenyaev** [comment]
We have reproduced the issue https://github.com/opencv/opencv-python/issues/572 on Ubuntu 21.04 and have tested a package which was built for this PR, it fixes a segfault error.

**Pull request merged**
